### Successful test: check response status is 200
GET http://localhost:8080/api/bp?url=https://www.bilibili.com/video/BV11s4y1Q7Yf/?spm_id_from=333.934.0.0&vd_source=7d38dd52ce866e656fec20561e6ad46d


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
GET http://localhost:8080/api/getvbyc?c=Your Category

###
GET https://api.bilibili.com/x/web-interface/view?bvid=BV1uz4y1Y7A5

###
GET http://localhost:8080/api/getvideo